### PR TITLE
PR#17 - Paging & Sorting Repositories.

### PR DESCRIPTION
**Pull request by leonplondon**
# Summary
Added paging support to BookController & UserController.
Added paging support to BoolRepository & UserRepository.
Refactored tests for implemented changes.

# Trello Card
https://trello.com/c/rTYNJaQJ/24-paging-and-sorting-repository

# Notes
Pointing to #16 because previous branches/PRs hasn't been merged yet.

### CODE REVIEW

**Review by rabinovichm — CHANGES_REQUESTED** [review]
Add tests to check the sorting and paging are working as expected. Eg: if in the request I say I want a page with size of 5 elements, it should not bring more than that.

**Comment by leonplondon** [comment]
> Add tests to check the sorting and paging are working as expected. Eg: if in the request I say I want a page with size of 5 elements, it should not bring more than that.

Refactored book/user repository tests to support paging at the DB integration level, because all calls with pageables to controllers are mocked at repository level.

**Review by rabinovichm — COMMENTED** [review]
Nice! Add tests to check the paging and sorting functionality from the controller and i swear that's it :yum:

**Review by rabinovichm — DISMISSED** [review]
Beautiful

**Review by IgnOliveto — DISMISSED** [review]

**Review by rabinovichm — APPROVED** [review]

**Review by IgnOliveto — APPROVED** [review]

**Pull request merged**
